#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.libreCMC2020 >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.libreCMC2020=/luci-static/librecmc2020
		set luci.main.mediaurlbase=/luci-static/librecmc2020
		commit luci
	EOF
fi

exit 0
